# Part III: Feature Engineering

## Basic settings

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import sys
import warnings
from datetime import datetime, timedelta

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

warnings.filterwarnings("ignore")
pd.options.display.max_rows = 50
pd.options.display.max_columns = None

In [3]:
src_path = os.path.abspath(os.path.join("..", "src"))
if src_path not in sys.path:
    sys.path.append(src_path)

In [4]:
from utils.utils import save_data

In [5]:
DATA_DIR = "../data"

## Load preprocessed data

In [6]:
df_sales = pd.read_csv(
    os.path.join(DATA_DIR, "sales_data_preprocessed.csv"), parse_dates=["date"]
)
df_weather = pd.read_csv(
    os.path.join(DATA_DIR, "weather_preprocessed.csv"), parse_dates=["date"]
)

## Feature Engineering

In [7]:
# Start by creating a copy of the sales dataframe
df_features = df_sales.copy()

### Separating train and test

In [8]:
# Test set will be the last 3 months of 2017 (Oct, Nov, Dec 2017)
cutoff_date = pd.Timestamp("2017-10-01")
print(f"Train-test split date: {cutoff_date}")

# Create a flag for train/test split
df_features["is_test"] = df_features["date"] >= cutoff_date
print(f"Training df_features: {len(df_features[~df_features['is_test']])} rows")
print(f"Test df_features: {len(df_features[df_features['is_test']])} rows")

# Merge weather df_features
df_features = pd.merge(
    df_features,
    df_weather[["date", "province", "temperature", "humidity", "season"]],
    on=["date", "province"],
    how="left",
)

display(df_features)

Train-test split date: 2017-10-01 00:00:00
Training df_features: 175725 rows
Test df_features: 25300 rows

,date,province,store_id,store_name,category,item_id,item_name,sales,is_test,temperature,humidity,season
0,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,1,Rice,17.0,False,13.4,87.8,winter
1,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,2,Noodles,10.0,False,13.4,87.8,winter
2,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,3,Bread,6.0,False,13.4,87.8,winter
3,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,4,Flour,8.0,False,13.4,87.8,winter
4,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,5,Cooking Oil,8.0,False,13.4,87.8,winter
...,...,...,...,...,...,...,...,...,...,...,...,...
201020,2017-12-31,Ho Chi Minh City,10,Binh Thanh Market,Baby & Health,31,Baby Wipes,41.0,True,25.9,67.7,dry
201021,2017-12-31,Ho Chi Minh City,10,Binh Thanh Market,Baby & Health,32,Pain Relievers,20.0,True,25.9,67.7,dry
201022,2017-12-31,Ho Chi Minh City,10,Binh Thanh Market,Baby & Health,33,Vitamins,19.0,True,25.9,67.7,dry
201023,2017-12-31,Ho Chi Minh City,10,Binh Thanh Market,Baby & Health,34,Cold & Flu Medicine,5.0,True,25.9,67.7,dry
201024,2017-12-31,Ho Chi Minh City,10,Binh Thanh Market,Baby & Health,35,First Aid Kit,12.0,True,25.9,67.7,dry

### Add date and holidays related features

In [9]:
# Date features
df_features["year"] = df_features["date"].dt.year
df_features["month"] = df_features["date"].dt.month
df_features["day"] = df_features["date"].dt.day
df_features["day_of_week"] = df_features["date"].dt.dayofweek
df_features["is_weekend"] = df_features["day_of_week"].apply(
    lambda x: 1 if x >= 5 else 0
)
df_features["quarter"] = df_features["date"].dt.quarter

# For simplicity in this PoC, we'll consider some major holidays
# In a real scenario, you would have a more comprehensive list based on the specific market
holidays = [
    # Example Vietnamese holidays (simplification)
    "2016-01-01",
    "2016-01-02",
    "2016-01-03",  # New Year
    "2016-04-16",
    "2016-04-17",
    "2016-04-18",  # Hung Kings Festival
    "2016-04-30",
    "2016-05-01",
    "2016-05-02",  # Reunification Day and May Day
    "2016-09-02",
    "2016-09-03",
    "2016-09-04",  # National Day
    "2017-01-01",
    "2017-01-02",  # New Year
    # Add more holidays as needed
]
holidays = pd.to_datetime(holidays)
df_features["is_holiday"] = df_features["date"].isin(holidays).astype(int)

df_features.head()

,date,province,store_id,store_name,category,item_id,item_name,sales,is_test,temperature,humidity,season,year,month,day,day_of_week,is_weekend,quarter,is_holiday
0,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,1,Rice,17.0,False,13.4,87.8,winter,2016,1,1,4,0,1,1
1,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,2,Noodles,10.0,False,13.4,87.8,winter,2016,1,1,4,0,1,1
2,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,3,Bread,6.0,False,13.4,87.8,winter,2016,1,1,4,0,1,1
3,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,4,Flour,8.0,False,13.4,87.8,winter,2016,1,1,4,0,1,1
4,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,5,Cooking Oil,8.0,False,13.4,87.8,winter,2016,1,1,4,0,1,1

### Weather-based features

In [10]:
# Temperature categories (using quantiles for even distribution)
temp_bins = [-np.inf, 20, 25, 30, np.inf]
temp_labels = ["Cold", "Cool", "Warm", "Hot"]
df_features["temp_category"] = pd.cut(
    df_features["temperature"], bins=temp_bins, labels=temp_labels
)

df_features.head()

,date,province,store_id,store_name,category,item_id,item_name,sales,is_test,temperature,humidity,season,year,month,day,day_of_week,is_weekend,quarter,is_holiday,temp_category
0,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,1,Rice,17.0,False,13.4,87.8,winter,2016,1,1,4,0,1,1,Cold
1,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,2,Noodles,10.0,False,13.4,87.8,winter,2016,1,1,4,0,1,1,Cold
2,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,3,Bread,6.0,False,13.4,87.8,winter,2016,1,1,4,0,1,1,Cold
3,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,4,Flour,8.0,False,13.4,87.8,winter,2016,1,1,4,0,1,1,Cold
4,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,5,Cooking Oil,8.0,False,13.4,87.8,winter,2016,1,1,4,0,1,1,Cold

In [11]:
# Humidity levels
humidity_bins = [-np.inf, 60, 75, np.inf]
humidity_labels = ["Low", "Medium", "High"]
df_features["humidity_level"] = pd.cut(
    df_features["humidity"], bins=humidity_bins, labels=humidity_labels
)

df_features.head()

,date,province,store_id,store_name,category,item_id,item_name,sales,is_test,temperature,humidity,season,year,month,day,day_of_week,is_weekend,quarter,is_holiday,temp_category,humidity_level
0,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,1,Rice,17.0,False,13.4,87.8,winter,2016,1,1,4,0,1,1,Cold,High
1,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,2,Noodles,10.0,False,13.4,87.8,winter,2016,1,1,4,0,1,1,Cold,High
2,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,3,Bread,6.0,False,13.4,87.8,winter,2016,1,1,4,0,1,1,Cold,High
3,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,4,Flour,8.0,False,13.4,87.8,winter,2016,1,1,4,0,1,1,Cold,High
4,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,5,Cooking Oil,8.0,False,13.4,87.8,winter,2016,1,1,4,0,1,1,Cold,High

In [12]:
# Convert categorical variables to numeric
df_features = pd.get_dummies(
    df_features, columns=["temp_category", "humidity_level", "season"], drop_first=True
)

df_features.head()

,date,province,store_id,store_name,category,item_id,item_name,sales,is_test,temperature,humidity,year,month,day,day_of_week,is_weekend,quarter,is_holiday,temp_category_Cool,temp_category_Warm,temp_category_Hot,humidity_level_Medium,humidity_level_High,season_fall,season_spring,season_summer,season_wet,season_winter
0,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,1,Rice,17.0,False,13.4,87.8,2016,1,1,4,0,1,1,False,False,False,False,True,False,False,False,False,True
1,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,2,Noodles,10.0,False,13.4,87.8,2016,1,1,4,0,1,1,False,False,False,False,True,False,False,False,False,True
2,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,3,Bread,6.0,False,13.4,87.8,2016,1,1,4,0,1,1,False,False,False,False,True,False,False,False,False,True
3,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,4,Flour,8.0,False,13.4,87.8,2016,1,1,4,0,1,1,False,False,False,False,True,False,False,False,False,True
4,2016-01-01,Hanoi,1,Hoan Kiem Market,Staples,5,Cooking Oil,8.0,False,13.4,87.8,2016,1,1,4,0,1,1,False,False,False,False,True,False,False,False,False,True

### Last n days sales

In [13]:
# Sort df_features by date, store, and item for proper lag feature creation
df_features = df_features.sort_values(["date", "store_name", "item_name"])

# Create an identifier for store-item combinations for grouping
df_features["store_item"] = df_features["store_name"] + "_" + df_features["item_name"]

In [14]:
# Create lag features for sales - last n days
for n in [1, 7, 14, 28]:
    # Group by store_item and create lag features
    df_features[f"sales_lag_{n}"] = df_features.groupby("store_item")[
        "sales"
    ].transform(lambda x: x.shift(n))

### Rolling average features

In [15]:
# Create rolling average features
for window in [7, 14, 28]:
    # Mean of last n days
    df_features[f"sales_mean_{window}d"] = df_features.groupby("store_item")[
        "sales"
    ].transform(lambda x: x.shift(1).rolling(window=window, min_periods=1).mean())

    # Min of last n days
    df_features[f"sales_min_{window}d"] = df_features.groupby("store_item")[
        "sales"
    ].transform(lambda x: x.shift(1).rolling(window=window, min_periods=1).min())

    # Max of last n days
    df_features[f"sales_max_{window}d"] = df_features.groupby("store_item")[
        "sales"
    ].transform(lambda x: x.shift(1).rolling(window=window, min_periods=1).max())

    # Standard deviation of last n days
    df_features[f"sales_std_{window}d"] = df_features.groupby("store_item")[
        "sales"
    ].transform(lambda x: x.shift(1).rolling(window=window, min_periods=1).std())

In [16]:
df_features.query("store_item == 'Ba Dinh Supermarket_Baby Wipes'")
# .to_csv("../data/check_data_01.csv", index=False)

,date,province,store_id,store_name,category,item_id,item_name,sales,is_test,temperature,humidity,year,month,day,day_of_week,is_weekend,quarter,is_holiday,temp_category_Cool,temp_category_Warm,temp_category_Hot,humidity_level_Medium,humidity_level_High,season_fall,season_spring,season_summer,season_wet,season_winter,store_item,sales_lag_1,sales_lag_7,sales_lag_14,sales_lag_28,sales_mean_7d,sales_min_7d,sales_max_7d,sales_std_7d,sales_mean_14d,sales_min_14d,sales_max_14d,sales_std_14d,sales_mean_28d,sales_min_28d,sales_max_28d,sales_std_28d
53,2016-01-01,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,12.0,False,13.4,87.8,2016,1,1,4,0,1,1,False,False,False,False,True,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
328,2016-01-02,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,22.0,False,15.2,75.2,2016,1,2,5,1,1,1,False,False,False,False,True,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,12.0,NaN,NaN,NaN,12.000000,12.0,12.0,NaN,12.000000,12.0,12.0,NaN,12.000000,12.0,12.0,NaN
603,2016-01-03,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,27.0,False,19.2,86.0,2016,1,3,6,1,1,1,False,False,False,False,True,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,22.0,NaN,NaN,NaN,17.000000,12.0,22.0,7.071068,17.000000,12.0,22.0,7.071068,17.000000,12.0,22.0,7.071068
878,2016-01-04,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,17.0,False,12.8,85.4,2016,1,4,0,0,1,0,False,False,False,False,True,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,27.0,NaN,NaN,NaN,20.333333,12.0,27.0,7.637626,20.333333,12.0,27.0,7.637626,20.333333,12.0,27.0,7.637626
1153,2016-01-05,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,19.0,False,16.8,88.3,2016,1,5,1,0,1,0,False,False,False,False,True,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,17.0,NaN,NaN,NaN,19.500000,12.0,27.0,6.454972,19.500000,12.0,27.0,6.454972,19.500000,12.0,27.0,6.454972
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199703,2017-12-27,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,46.0,True,20.0,79.9,2017,12,27,2,0,4,0,False,False,False,False,True,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,32.0,38.0,24.0,24.0,41.428571,32.0,53.0,7.230886,39.214286,24.0,53.0,7.464568,35.178571,21.0,53.0,8.304633
199978,2017-12-28,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,35.0,True,17.2,67.2,2017,12,28,3,0,4,0,False,False,False,True,False,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,46.0,41.0,44.0,24.0,42.571429,32.0,53.0,7.230886,40.785714,32.0,53.0,6.228700,35.964286,21.0,53.0,8.248376
200253,2017-12-29,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,46.0,True,21.0,76.1,2017,12,29,4,0,4,0,True,False,False,False,True,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,35.0,35.0,40.0,28.0,41.714286,32.0,53.0,7.782765,40.142857,32.0,53.0,6.334972,36.357143,21.0,53.0,7.912551
200528,2017-12-30,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,56.0,True,20.9,80.8,2017,12,30,5,1,4,0,True,False,False,False,True,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,46.0,44.0,44.0,21.0,43.285714,32.0,53.0,7.296444,40.571429,32.0,53.0,6.524678,37.000000,21.0,53.0,7.939587
200803,2017-12-31,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,69.0,True,15.3,70.7,2017,12,31,6,1,4,0,False,False,False,True,False,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,56.0,53.0,42.0,37.0,45.000000,32.0,56.0,8.755950,41.428571,32.0,56.0,7.693297,38.250000,24.0,56.0,8.081185

### Exponentially weighted moving average

In [17]:
# Exponentially weighted moving average
for alpha in [0.5, 0.75]:
    for window in [7, 14, 28]:
        # Create an EWMA feature
        alpha_str = str(alpha).replace(".", "")
        df_features[f"sales_ewma_{window}d_a{alpha_str}"] = df_features.groupby(
            "store_item"
        )["sales"].transform(lambda x: x.shift(1).ewm(alpha=alpha).mean())

In [18]:
df_features.query("store_item == 'Ba Dinh Supermarket_Baby Wipes'")

,date,province,store_id,store_name,category,item_id,item_name,sales,is_test,temperature,humidity,year,month,day,day_of_week,is_weekend,quarter,is_holiday,temp_category_Cool,temp_category_Warm,temp_category_Hot,humidity_level_Medium,humidity_level_High,season_fall,season_spring,season_summer,season_wet,season_winter,store_item,sales_lag_1,sales_lag_7,sales_lag_14,sales_lag_28,sales_mean_7d,sales_min_7d,sales_max_7d,sales_std_7d,sales_mean_14d,sales_min_14d,sales_max_14d,sales_std_14d,sales_mean_28d,sales_min_28d,sales_max_28d,sales_std_28d,sales_ewma_7d_a05,sales_ewma_14d_a05,sales_ewma_28d_a05,sales_ewma_7d_a075,sales_ewma_14d_a075,sales_ewma_28d_a075
53,2016-01-01,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,12.0,False,13.4,87.8,2016,1,1,4,0,1,1,False,False,False,False,True,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
328,2016-01-02,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,22.0,False,15.2,75.2,2016,1,2,5,1,1,1,False,False,False,False,True,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,12.0,NaN,NaN,NaN,12.000000,12.0,12.0,NaN,12.000000,12.0,12.0,NaN,12.000000,12.0,12.0,NaN,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
603,2016-01-03,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,27.0,False,19.2,86.0,2016,1,3,6,1,1,1,False,False,False,False,True,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,22.0,NaN,NaN,NaN,17.000000,12.0,22.0,7.071068,17.000000,12.0,22.0,7.071068,17.000000,12.0,22.0,7.071068,18.666667,18.666667,18.666667,20.000000,20.000000,20.000000
878,2016-01-04,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,17.0,False,12.8,85.4,2016,1,4,0,0,1,0,False,False,False,False,True,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,27.0,NaN,NaN,NaN,20.333333,12.0,27.0,7.637626,20.333333,12.0,27.0,7.637626,20.333333,12.0,27.0,7.637626,23.428571,23.428571,23.428571,25.333333,25.333333,25.333333
1153,2016-01-05,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,19.0,False,16.8,88.3,2016,1,5,1,0,1,0,False,False,False,False,True,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,17.0,NaN,NaN,NaN,19.500000,12.0,27.0,6.454972,19.500000,12.0,27.0,6.454972,19.500000,12.0,27.0,6.454972,20.000000,20.000000,20.000000,19.058824,19.058824,19.058824
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199703,2017-12-27,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,46.0,True,20.0,79.9,2017,12,27,2,0,4,0,False,False,False,False,True,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,32.0,38.0,24.0,24.0,41.428571,32.0,53.0,7.230886,39.214286,24.0,53.0,7.464568,35.178571,21.0,53.0,8.304633,39.428568,39.428568,39.428568,35.954064,35.954064,35.954064
199978,2017-12-28,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,35.0,True,17.2,67.2,2017,12,28,3,0,4,0,False,False,False,True,False,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,46.0,41.0,44.0,24.0,42.571429,32.0,53.0,7.230886,40.785714,32.0,53.0,6.228700,35.964286,21.0,53.0,8.248376,42.714284,42.714284,42.714284,43.488516,43.488516,43.488516
200253,2017-12-29,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,46.0,True,21.0,76.1,2017,12,29,4,0,4,0,True,False,False,False,True,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,35.0,35.0,40.0,28.0,41.714286,32.0,53.0,7.782765,40.142857,32.0,53.0,6.334972,36.357143,21.0,53.0,7.912551,38.857142,38.857142,38.857142,37.122129,37.122129,37.122129
200528,2017-12-30,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,56.0,True,20.9,80.8,2017,12,30,5,1,4,0,True,False,False,False,True,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,46.0,44.0,44.0,21.0,43.285714,32.0,53.0,7.296444,40.571429,32.0,53.0,6.524678,37.000000,21.0,53.0,7.939587,42.428571,42.428571,42.428571,43.780532,43.780532,43.780532
200803,2017-12-31,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,69.0,True,15.3,70.7,2017,12,31,6,1,4,0,False,False,False,True,False,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,56.0,53.0,42.0,37.0,45.000000,32.0,56.0,8.755950,41.428571,32.0,56.0,7.693297,38.250000,24.0,56.0,8.081185,49.214286,49.214286,49.214286,52.945133,52.945133,52.945133

### Store-level features

In [19]:
# Mean and sum of store sales in the last 7 days
df_features["store_mean_7d"] = df_features.groupby(["store_name", "date"])[
    "sales"
].transform("mean")
df_features["store_sum_7d"] = df_features.groupby(["store_name", "date"])[
    "sales"
].transform("sum")

### Item-level features

In [20]:
# Mean and sum of item sales in the last 7 days
df_features["item_mean_7d"] = df_features.groupby(["item_name", "date"])[
    "sales"
].transform("mean")
df_features["item_sum_7d"] = df_features.groupby(["item_name", "date"])[
    "sales"
].transform("sum")

In [21]:
df_features.query("store_item == 'Ba Dinh Supermarket_Baby Wipes'")

,date,province,store_id,store_name,category,item_id,item_name,sales,is_test,temperature,humidity,year,month,day,day_of_week,is_weekend,quarter,is_holiday,temp_category_Cool,temp_category_Warm,temp_category_Hot,humidity_level_Medium,humidity_level_High,season_fall,season_spring,season_summer,season_wet,season_winter,store_item,sales_lag_1,sales_lag_7,sales_lag_14,sales_lag_28,sales_mean_7d,sales_min_7d,sales_max_7d,sales_std_7d,sales_mean_14d,sales_min_14d,sales_max_14d,sales_std_14d,sales_mean_28d,sales_min_28d,sales_max_28d,sales_std_28d,sales_ewma_7d_a05,sales_ewma_14d_a05,sales_ewma_28d_a05,sales_ewma_7d_a075,sales_ewma_14d_a075,sales_ewma_28d_a075,store_mean_7d,store_sum_7d,item_mean_7d,item_sum_7d
53,2016-01-01,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,12.0,False,13.4,87.8,2016,1,1,4,0,1,1,False,False,False,False,True,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.071429,478.000000,23.833333,143.0
328,2016-01-02,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,22.0,False,15.2,75.2,2016,1,2,5,1,1,1,False,False,False,False,True,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,12.0,NaN,NaN,NaN,12.000000,12.0,12.0,NaN,12.000000,12.0,12.0,NaN,12.000000,12.0,12.0,NaN,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,20.785714,582.000000,29.666667,178.0
603,2016-01-03,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,27.0,False,19.2,86.0,2016,1,3,6,1,1,1,False,False,False,False,True,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,22.0,NaN,NaN,NaN,17.000000,12.0,22.0,7.071068,17.000000,12.0,22.0,7.071068,17.000000,12.0,22.0,7.071068,18.666667,18.666667,18.666667,20.000000,20.000000,20.000000,23.964286,671.000000,35.166667,211.0
878,2016-01-04,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,17.0,False,12.8,85.4,2016,1,4,0,0,1,0,False,False,False,False,True,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,27.0,NaN,NaN,NaN,20.333333,12.0,27.0,7.637626,20.333333,12.0,27.0,7.637626,20.333333,12.0,27.0,7.637626,23.428571,23.428571,23.428571,25.333333,25.333333,25.333333,16.661000,466.507994,24.333333,146.0
1153,2016-01-05,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,19.0,False,16.8,88.3,2016,1,5,1,0,1,0,False,False,False,False,True,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,17.0,NaN,NaN,NaN,19.500000,12.0,27.0,6.454972,19.500000,12.0,27.0,6.454972,19.500000,12.0,27.0,6.454972,20.000000,20.000000,20.000000,19.058824,19.058824,19.058824,18.071429,506.000000,25.500000,153.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199703,2017-12-27,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,46.0,True,20.0,79.9,2017,12,27,2,0,4,0,False,False,False,False,True,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,32.0,38.0,24.0,24.0,41.428571,32.0,53.0,7.230886,39.214286,24.0,53.0,7.464568,35.178571,21.0,53.0,8.304633,39.428568,39.428568,39.428568,35.954064,35.954064,35.954064,37.250000,1043.000000,57.000000,342.0
199978,2017-12-28,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,35.0,True,17.2,67.2,2017,12,28,3,0,4,0,False,False,False,True,False,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,46.0,41.0,44.0,24.0,42.571429,32.0,53.0,7.230886,40.785714,32.0,53.0,6.228700,35.964286,21.0,53.0,8.248376,42.714284,42.714284,42.714284,43.488516,43.488516,43.488516,33.803857,946.507994,53.166667,319.0
200253,2017-12-29,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,46.0,True,21.0,76.1,2017,12,29,4,0,4,0,True,False,False,False,True,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,35.0,35.0,40.0,28.0,41.714286,32.0,53.0,7.782765,40.142857,32.0,53.0,6.334972,36.357143,21.0,53.0,7.912551,38.857142,38.857142,38.857142,37.122129,37.122129,37.122129,32.375286,906.507994,57.000000,342.0
200528,2017-12-30,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,56.0,True,20.9,80.8,2017,12,30,5,1,4,0,True,False,False,False,True,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,46.0,44.0,44.0,21.0,43.285714,32.0,53.0,7.296444,40.571429,32.0,53.0,6.524678,37.000000,21.0,53.0,7.939587,42.428571,42.428571,42.428571,43.780532,43.780532,43.780532,46.572571,1304.031977,78.833333,473.0
200803,2017-12-31,Hanoi,2,Ba Dinh Supermarket,Baby & Health,31,Baby Wipes,69.0,True,15.3,70.7,2017,12,31,6,1,4,0,False,False,False,True,False,False,False,False,False,True,Ba Dinh Supermarket_Baby Wipes,56.0,53.0,42.0,37.0,45.000000,32.0,56.0,8.755950,41.428571,32.0,56.0,7.693297,38.250000,24.0,56.0,8.081185,49.214286,49.214286,49.214286,52.945133,52.945133,52.945133,39.822000,1115.015989,76.666667,460.0

In [22]:
# Drop rows with NaN (these will be the first n days without lag features)
df_features = df_features.dropna()

## Save feature engineered data

In [23]:
df_features.info()

<class 'pandas.core.frame.DataFrame'>
Index: 193325 entries, 7752 to 200845
Data columns (total 55 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   date                   193325 non-null  datetime64[ns]
 1   province               193325 non-null  object
 2   store_id               193325 non-null  int64
 3   store_name             193325 non-null  object
 4   category               193325 non-null  object
 5   item_id                193325 non-null  int64
 6   item_name              193325 non-null  object
 7   sales                  193325 non-null  float64
 8   is_test                193325 non-null  bool
 9   temperature            193325 non-null  float64
 10  humidity               193325 non-null  float64
 11  year                   193325 non-null  int32
 12  month                  193325 non-null  int32
 13  day                    193325 non-null  int32
 14  day_of_week            193325 non-null  int32
 15  is_weekend             193325 non-null  int64
 16  quarter                193325 non-null  int32
 17  is_holiday             193325 non-null  int64
 18  temp_category_Cool     193325 non-null  bool
 19  temp_category_Warm     193325 non-null  bool
 20  temp_category_Hot      193325 non-null  bool
 21  humidity_level_Medium  193325 non-null  bool
 22  humidity_level_High    193325 non-null  bool
 23  season_fall            193325 non-null  bool
 24  season_spring          193325 non-null  bool
 25  season_summer          193325 non-null  bool
 26  season_wet             193325 non-null  bool
 27  season_winter          193325 non-null  bool
 28  store_item             193325 non-null  object
 29  sales_lag_1            193325 non-null  float64
 30  sales_lag_7            193325 non-null  float64
 31  sales_lag_14           193325 non-null  float64
 32  sales_lag_28           193325 non-null  float64
 33  sales_mean_7d          193325 non-null  float64
 34  sales_min_7d           193325 non-null  float64
 35  sales_max_7d           193325 non-null  float64
 36  sales_std_7d           193325 non-null  float64
 37  sales_mean_14d         193325 non-null  float64
 38  sales_min_14d          193325 non-null  float64
 39  sales_max_14d          193325 non-null  float64
 40  sales_std_14d          193325 non-null  float64
 41  sales_mean_28d         193325 non-null  float64
 42  sales_min_28d          193325 non-null  float64
 43  sales_max_28d          193325 non-null  float64
 44  sales_std_28d          193325 non-null  float64
 45  sales_ewma_7d_a05      193325 non-null  float64
 46  sales_ewma_14d_a05     193325 non-null  float64
 47  sales_ewma_28d_a05     193325 non-null  float64
 48  sales_ewma_7d_a075     193325 non-null  float64
 49  sales_ewma_14d_a075    193325 non-null  float64
 50  sales_ewma_28d_a075    193325 non-null  float64
 51  store_mean_7d          193325 non-null  float64
 52  store_sum_7d           193325 non-null  float64
 53  item_mean_7d           193325 non-null  float64
 54  item_sum_7d            193325 non-null  float64
dtypes: bool(11), datetime64[ns](1), float64(29), int32(5), int64(4), object(5)
memory usage: 64.7+ MB

In [24]:
# PATH
num_features = df_features.shape[1]
save_path = os.path.join(DATA_DIR, f"feature_engineered_data_{num_features}_features.feather")
save_path

'../data/feature_engineered_data_55_features.feather'

In [25]:
# Save data
save_data(df_features, save_path, file_format='feather')

DataFrame saved to ../data/feature_engineered_data_55_features.feather in Feather format.